@yield("layout")
@section("content")
<section>
    <div>
        <div>
            <h1>Forex Major</h1>
            <p>Audusd</p>
            <p>eurusd</p>
            <p>gbpusd</p>
            <p>nzdusd</p>
            <p>usdusd</p>
            <p>usdchf</p>
            <p>usdjpy</p>
        </div>
    </div>
    <div>
        <div>
            <h1>Forex Minors</h1>
            <p>Audcad</p>
            <p>cadchf</p>
            <p>eurgbp</p>
            <p>gbpcad</p>
            <p>nzdcad</p>
            <p>audchf</p>
            <p>cadjpy</p>
            <p>eurjpy</p>
            <p>gbpchf</p>
            <p>nzdchf</p>
            <p>audjpy</p>
            <p>euraud</p>
            <p>eurnzd</p>
            <p>gbpjpy</p>
            <p>nzdjpy</p>
            <p>audnzd</p>
            <p>eurcad</p>
            <p>gbpaud</p>
            <p>gbpnzd</p>
        </div>
        <div>
            <h1>Forex Exotics</h1>
            <p>Eurnok</p>
            <p>usdnok</p>
            <p>eurtry</p>
            <p>usdczk</p>
            <p>usdhkd</p>
            <p>gbpnok</p>
            <p>eurhkd</p>
            <p>cadsgd</p>
            <p>chfnok</p>
            <p>gbphuf</p>
            <p>noksek</p>
            <p>sgdjpy</p>
            <p>nzdsgd</p>
            <p>eursek</p>
            <p>usdsek</p>
            <p>eurzar</p>
            <p>usdhuf</p>
            <p>usdzar</p>
            <p>usdpln</p>
            <p>gbppln</p>
            <p>eurmxn</p>
            <p>chfhuf</p>
            <p>Hdkjpy</p>
            <p>Eurpln</p>
            <p>tryjpy</p>
            <p>nokjpy</p>
            <p>eurczk</p>
            <p>gbptry</p>
            <p>usdmxn</p>
            <p>eurrub</p>
            <p>usdsgd</p>
            <p>gbpsgd</p>
            <p>eursgd</p>
            <p>chfdkk</p>
            <p>gbpdkk</p>
            <p>zarjpy</p>
            <p>usddkk</p>
            <p>eurhuf</p>
            <p>gbpzar</p>
            <p>usdrub</p>
            <p>usdcnh</p>
            <p>gbphkd</p>
            <p>gbpsek</p>
            <p>noksek</p>
        </div>
        <div>
            <h1>Forex Majors</h1>
            <p>Audusd</p>
            <p>eurusd</p>
            <p>gbpusd</p>
            <p>nzdusd</p>
            <p>usdcad</p>
            <p>usdchf</p>
            <p>usdjpy</p>
        </div>
        <div>
            <h1>Forex Majors</h1>
            <p>xageur</p>
            <p>xagusd</p>
            <p>xaueur</p>
            <p>xauusd</p>
            <p>xpdusd</p>
            <p>xptusd</p>
            <p>xauaud</p>
        </div>
        <div>
            <h1>indices</h1>
            <p>aus200</p>
            <p>uk100</p>
            <p>spx500</p>
            <p>de30</p>
            <p>jp225</p>
            <p>us30</p>
            <p>f40</p>
            <p>nas100</p>
        </div>
        <div>
            <h1>energies</h1>
            <p>ngas</p>
            <p>ukoil</p>
            <p>usoil</p>
        </div>
        <div>
            <h1>futures</h1>
            <p>cocoa</p>
            <p>coffee</p>
            <p>copper</p>
            <p>cotton</p>
            <p>sugar</p>
        </div>
        <div>
            <h1>crypto</h1>
            <p>btcusd</p>
            <p>neousd</p>
            <p>zecusd</p>
            <p>bnbusd</p>
            <p>edousd</p>
            <p>bcheur</p>
            <p>ethgbp</p>
            <p>adausd</p>
            <p>ethusd</p>
            <p>eosusd</p>
            <p>omgusd</p>
            <p>dasusd</p>
            <p>etcusd</p>
            <p>etcusd</p>
            <p>btceur</p>
            <p>ltceur</p>
            <p>ltcusd</p>
            <p>etpusd</p>
            <p>sanusd</p>
            <p>iotusd</p>
            <p>xlmusd</p>
            <p>btcgbp</p>
            <p>ltcgbp</p>
            <p>xrpusd</p>
            <p>xmrusd</p>
            <p>trxusd</p>
            <p>qtuusd</p>
            <p>bchusd</p>
            <p>etheur</p>
            <p>dogeusd</p>
        </div>
        <div>
            <h1>stocks(shares)</h1>
            <p>adidas</p>
            <p>bbva</p>
            <p>daimler</p>
            <p>lufthansa</p>
            <p>societe</p>
            <p>aig</p>
            <p>amex</p>
            <p>boeing</p>
            <p>coca+cola</p>
            <p>fedex</p>
            <p>gm</p>
            <p>ibm</p>
            <p>microsoft</p>
            <p>oracle</p>
            <p>teva</p>
            <p>air+france</p>
            <p>bmw</p>
            <p>deutsche+bk</p>
            <p>Lvmh</p>
            <p>telefonica</p>
            <p>alibab</p>
            <p>apple</p>
            <p>chevron</p>
            <p>ebay</p>
            <p>ferrrari</p>
            <p>goldmans</p>
            <p>intel</p>
            <p>mstrcard</p>
            <p>p&g</p>
            <p>twitter</p>
        <p>allianz</p>
        <p>bnp</p>
        <p>deutsche+po</p>
        <p>santander</p>
        <p>total</p>
        <p>alphabet+c</p>
        <p>at&t</p>
        <p>cisco</p>
        <p>exxoin</p>
        <p>ford</p>
        <p>hilton</p>
        <p>johnson</p>
        <p>mcd</p>
        <p>pfizer</p>
        <p>visa</p>
        <p>bayer</p>
        <p>commerszbank</p>
        <p>eon</p>
        <p>volkswagen</p>
        <p>amazon</p>
        <p>bnk+amer</p>
        <p>citi</p>
        <p>facebook</p>
        <p>ge</p>
        <p>hp</p>
        <p>jpmorgan</p>
        <p>netflix</p>
        <p>tesla</p>
        </div>
    </div>
</section>
@endsection("content")